SpikeInterface/spiketoolkit

- examples/mountainsort4_example.ipynb
- notebooks/AnalyzerExample.ipynb
- setup.py
- spiketoolkit/Analyzer.py
- spiketoolkit/__init__.py
- spiketoolkit/sorters/__init__.py
- spiketoolkit/sorters/mountainsort4/__init__.py
- spiketoolkit/sorters/mountainsort4/mountainsort4.py
Add mountainsort4 spike sorter, update dependencies, create example
Also disabled Analyzer for the time being.
> add mountainsort4 and create example

- spiketoolkit/preprocessing/filterrecording.py
> filter chunks in parallel

- spiketoolkit/sorters/__init__.py
- spiketoolkit/sorters/tridesclous/__init__.py
- spiketoolkit/sorters/tridesclous/tests/.gitignore
- spiketoolkit/sorters/tridesclous/tests/test_tridesclous.py
- spiketoolkit/sorters/tridesclous/tridesclous.py
This is the very first step for tridesclous integration.
I also need to write ```TridesclousSortingExtractor``` in spikeextractor.
> [WIP] First step for tridesclous integration.

- spiketoolkit/sorters/basesorter.py
- spiketoolkit/sorters/ironclust/ironclust.py
- spiketoolkit/sorters/kilosort/kilosort.py
- spiketoolkit/sorters/klusta/klusta.py
- spiketoolkit/sorters/launcher.py
- spiketoolkit/sorters/mountainsort4/mountainsort4.py
- spiketoolkit/sorters/spyking_circus/spyking_circus.py
- spiketoolkit/sorters/tests/test_launcher.py
- spiketoolkit/sorters/tridesclous/tridesclous.py
Do not merge for now.
Several features:
* Save raw file in tridesclous less memory agressive.
* laucher save run time for each sroter/recording in csv
> [WIP] Several new features

- spiketoolkit/sorters/herdingspikes/__init__.py
- spiketoolkit/sorters/herdingspikes/herdingspikes.py
- spiketoolkit/sorters/sorterlist.py
This seems to work, at least for me, and we can discuss together.
What I would like to do is to remove some of the default parameters so that the user is forced to set them manually, but I'm not sure what's the best way to do this.
> Add herdingspikes support

- spiketoolkit/sorters/__init__.py
- spiketoolkit/sorters/launcher.py
- spiketoolkit/sorters/tests/test_launcher.py
Some features in laucher:
* Collect results in a nested dict for all recording and sorter with laucher.
> New feature in launcher

- spiketoolkit/sorters/klusta/klusta.py
fixed a bug in lusta and using int16 by default
> fixed klusta - using int16

- spiketoolkit/postprocessing/__init__.py
- spiketoolkit/preprocessing/__init__.py
- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/sorters/basesorter.py
- spiketoolkit/sorters/launcher.py
- spiketoolkit/sorters/mountainsort4/mountainsort4.py
> Exposed all objects for GUI

- spiketoolkit/sorters/herdingspikes/herdingspikes.py
- spiketoolkit/sorters/ironclust/ironclust.py
Some changes to the HS2 sorter class.
> Now saves the sampling rate, also minor default parameter adjustments

- spiketoolkit/preprocessing/preprocessinglist.py
- spiketoolkit/preprocessing/transform_traces.py
Traces will be scaled by: traces*scalar + offset in this preprocessing tool. Is this what you had in mind Matthias?
> scale_traces --> transform_traces

- spiketoolkit/sorters/herdingspikes/herdingspikes.py
Cf. #68. I went for fully flat here, which is perhaps a bit confusing to the user who doesn't know what needs to be tweaked, but I suppose that's more of a problem of HS rather than spiketoolkit.
> flat dictionary for hs

- spiketoolkit/sorters/ironclust/ironclust.py
- spiketoolkit/sorters/kilosort/kilosort.py
- spiketoolkit/sorters/kilosort2/kilosort2.py
Enhance environ path for KS, KS2 and IronClust
> Enhance environ path for KS, KS2 and IronClust

- spiketoolkit/sorters/ironclust/ironclust.py
- spiketoolkit/sorters/kilosort/kilosort.py
- spiketoolkit/sorters/kilosort2/kilosort2.py
Still improve the logic of global path in KS, KS2 and Ironclust.
This is because path can be change at everytime in two way (by call function or os.environ)
> Still improve the logic of global path in KS, KS2 and Ironclust.

- .travis.yml
- spiketoolkit/postprocessing/postprocessing_tools.py
- Fixes a bug in setting the right pc feature indexes for the template gui
- Clean up comments
> Fixes to export to phy pc_feature_ind

- setup.py
- spiketoolkit/sorters/herdingspikes/herdingspikes.py
Name of the function was changed, and not implemented here.
> Fix for pre_scaling function call.

- spiketoolkit/comparison/multisortingcomparison.py
Tollerance --> tolerance (no functionality changed)
> Fixed typo in variable name

- spiketoolkit/comparison/tests/test_groundtruthstudy.py
- spiketoolkit/sorters/tests/common_tests.py
- spiketoolkit/sorters/tests/test_launcher.py
- spiketoolkit/sorters/tests/test_tridesclous.py
> Fixed seed in travis tests

- docs/postprocessing_example.rst
- examples/postprocessing_example.ipynb
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/postprocessinglist.py
- spiketoolkit/validation/qualitymetrics.py
I think I propagated everything correctly (with find all and replace all). Maybe someone could check to make sure.
We can discuss name changes here so I won't merge yet.
> Name changes to postprocessing modules

- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/groundtruthstudy.py
> Big agregate of all individual results.

- spiketoolkit/postprocessing/postprocessing_tools.py
- the `r` in front of the path is Windows proof
- removed duplicate metadata
> small bug fixes to export to phy

- docs/postprocessing_example.rst
- examples/curation_example.ipynb
- examples/sorters_example.ipynb
- setup.py
- spiketoolkit/__init__.py
- spiketoolkit/curation/CurationSortingExtractor.py
- spiketoolkit/curation/__init__.py
- spiketoolkit/curation/curationlist.py
- spiketoolkit/curation/tests/test_curation.py
- spiketoolkit/curation/threshold_max_ISI.py
- spiketoolkit/curation/threshold_min_SNR.py
- spiketoolkit/curation/threshold_min_num_spikes.py
- spiketoolkit/postprocessing/postprocessinglist.py
- spiketoolkit/sorters/__init__.py
- spiketoolkit/sorters/launcher.py
Propagating curation to spiketoolkit
> Moved curation to spiketoolkit

- spiketoolkit/comparison/basecomparison.py
- spiketoolkit/comparison/comparisontools.py
- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/groundtruthstudy.py
- spiketoolkit/comparison/multisortingcomparison.py
- spiketoolkit/comparison/sortingcomparison.py
- spiketoolkit/comparison/tests/test_comparisontools.py
- spiketoolkit/comparison/tests/test_groundtruthcomparison.py
- spiketoolkit/comparison/tests/test_multisortingcomparison.py
- spiketoolkit/comparison/tests/test_sortingcomparison.py
This fixes this issue https://github.com/SpikeInterface/spiketoolkit/issues/128
@jamesjun @magland when we merge we should propagate this change in SpikeForest
> Matching based on time instead of number of frames

- spiketoolkit/comparison/basecomparison.py
- spiketoolkit/comparison/comparisontools.py
- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/sortingcomparison.py
- makes labeling optional (True by default for groundtruth)
- makes misclassification error computation optional (False by default)
> Make miclassification error optional (it can be very time consuming)

- spiketoolkit/comparison/basecomparison.py
- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/sortingcomparison.py
* label > compute_label
* template_txt_performance depend on self._compute_misclassification
* compute_misclassification=True for GroundTruthSoringComparison.
> Some other change about the compute_misclassification option.

- .travis.yml
- spiketoolkit/comparison/comparisontools.py
Fix bug when units is empty : for dtype=U
> Fix bug when units is empty : for dtype=U

- MANIFEST.in
- setup.py
the spike sorting relate files are now in the spikesorters package
> removed manifest

- spiketoolkit/comparison/comparisontools.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- remove start_frame and end_frame from postpsocessing functions (it was not used)
- added `channels` param to get_waveforms
> Postprocessing cleanup

- spiketoolkit/comparison/basecomparison.py
- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/multisortingcomparison.py
- spiketoolkit/sorters/launcher.py
- spiketoolkit/sorters/tests/test_launcher.py
- spiketoolkit/study/groundtruthstudy.py
- spiketoolkit/study/studytools.py
- spiketoolkit/study/test/test_groundtruthstudy.py
- fix redundant / false positive units
> Comparison small fixes

- examples/quality_metrics_curation_example.ipynb
- spiketoolkit/validation/__init__.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
This one's for you @alejoe91. :D
> functional calls for all metrics

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/clip_traces.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/preprocessinglist.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform_traces.py
- spiketoolkit/preprocessing/whiten.py
and gui name changes in preprocessors.
> named changed ResampledRecording-->ResampleRecording

- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_tools.py
@colehurwitz this is what I meant! :)
When you compute a metric, you can save the metric as unit property (default)
> save qc as properties and code cleanup

- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
- remove printProgressBar by default
- in compute_isi: if sampling_frequency is none, get it from sorting
> Added verbose option

- spiketoolkit/validation/metric_calculator.py
@colehurwitz 
this allows to register the recording_extractor at the __init__ of MetricCalculator
> allow for instantiation of recording in metric calculator init

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_preprocessing.py
I also changed functionality in bad_channels. We never use 'auto' anywhere else in SpikeInterface so I made that None instead. What do you think @alejoe91 ?
> Name changes

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/whiten.py
> filter params exposed in subclasses

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/validation/metric_calculator.py
fixes https://github.com/SpikeInterface/spiketoolkit/issues/240
> Fix template when sparse waveforms

- spiketoolkit/curation/threshold_firing_rate.py
- spiketoolkit/curation/threshold_isi_violations.py
- spiketoolkit/curation/threshold_num_spikes.py
- spiketoolkit/curation/threshold_presence_ratio.py
- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/curation/thresholdcurator.py
- spiketoolkit/postprocessing/postprocessing_tools.py
Added 2 more signals to the base ThresholdCurator: '<=' and '>='
> Added '<=' and '>=' to ThresholdCurator

- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_tools.py
@alejoe91 @samuelgarcia Is this a sensible default value?
> refactoring names in postprocessing and quality metrics

- spiketoolkit/curation/threshold_snr.py
> exposed all parameters in threshold_snr

- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/validation_tools.py
removed channel map as it is no longer used.
> fixed bug in metric data

- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/whiten.py
Random seeds for all preprocessors.
> random seeds for preprocessors

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/validation/metric_calculator.py
* Make FilteredChunkCache optional.
* name cache cache_on_file
* avoid concatenate.
> Some cache change for filtering.

- spiketoolkit/postprocessing/postprocessing_tools.py
There is no need to save waveforms when exporting to phy (this was form an old attempt)
> No need to save waveforms to phy

- spiketoolkit/curation/threshold_firing_rate.py
- spiketoolkit/curation/threshold_isi_violations.py
- spiketoolkit/curation/threshold_num_spikes.py
- spiketoolkit/curation/threshold_presence_ratio.py
- spiketoolkit/curation/threshold_snr.py
Removed all curation defaults. Anyone using curation should know the threshold and sign of the metric, defaults are misleading.
> removed all defaults for threshold and sign

- spiketoolkit/curation/threshold_snr.py
> removed redundant params

- .gitignore
- spiketoolkit/curation/curationlist.py
- spiketoolkit/curation/threshold_silhouette_score.py
- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/tests/test_curation.py
@colehurwitz Added ``threshold_silhouette_score.py`` and associated tests and configuration settings.
> Silhouette

- spiketoolkit/curation/curationlist.py
- spiketoolkit/curation/threshold_amplitude_cutoff.py
- spiketoolkit/curation/threshold_d_primes.py
- spiketoolkit/curation/threshold_l_ratios.py
- spiketoolkit/curation/threshold_silhouette_score.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/validation/__init__.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
In addition to implementing `threshold_amplitude_cutoff` and its associated bits and pieces, I ran a PEP 8 formatter over `quality_metrics` and `metric_calculator` that may not be to your liking. ;)
> Implemented threshold_amplitude_cutoff.  General code cleanup.

- spiketoolkit/postprocessing/postprocessing_tools.py
- force dtype of output files
- remove unised properties
- only visualize 16 channels per template (essential for HD-MEAs, the number of channels is adjustable by the user)
> Updates for Phy2

- spiketoolkit/preprocessing/filterrecording.py
> Fix filter get_traces when single channel is used

- spiketoolkit/postprocessing/postprocessing_tools.py
Fixes for PCA indexing https://github.com/SpikeInterface/spiketoolkit/issues/300
> Fix pca indexing

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_curation_extractor.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
- spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py
- waveforms are saved as memmap arrays
- amplitude as well
- WIP for pca scores and export to phy
This should make it possible to deal with large recordings, and also to export to phy in chunks
> Memmap postprocessing tools

- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/drift_metric.py
- spiketoolkit/validation/quality_metric_classes/firing_rate.py
- spiketoolkit/validation/quality_metric_classes/isi_violation.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/presence_ratio.py
- spiketoolkit/validation/quality_metric_classes/quality_metric.py
- spiketoolkit/validation/quality_metric_classes/silhouette_score.py
- spiketoolkit/validation/quality_metric_classes/snr.py
Setting all the infinities to None
> fix epochs

- spiketoolkit/curation/threshold_metrics.py
- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/clip_traces.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform_traces.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/tests/utils.py
- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/utils/thresholdcurator.py
https://github.com/SpikeInterface/spikeextractors/pull/316
this allows to save preprocesisng and curation steps to json
> Serialize preprocessors and curators

- spiketoolkit/postprocessing/postprocessing_tools.py
https://github.com/SpikeInterface/spiketoolkit/issues/310
> Compute similarity using correct template indexes

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py
https://github.com/SpikeInterface/spiketoolkit/issues/306
> Optional computation of pc features when exporting to phy

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/clip.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/drift_metric.py
- spiketoolkit/validation/quality_metric_classes/firing_rate.py
- spiketoolkit/validation/quality_metric_classes/isi_violation.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/parameter_dictionaries.py
- spiketoolkit/validation/quality_metric_classes/presence_ratio.py
- spiketoolkit/validation/quality_metric_classes/silhouette_score.py
- spiketoolkit/validation/quality_metric_classes/snr.py
@alejoe91 , removed all gui params for later addition to spikely.
> removed gui params

- spiketoolkit/curation/threshold_metrics.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/postprocessinglist.py
- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/transform.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/tests/utils.py
- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/drift_metric.py
- spiketoolkit/validation/quality_metric_classes/firing_rate.py
- spiketoolkit/validation/quality_metric_classes/isi_violation.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/parameter_dictionaries.py
- spiketoolkit/validation/quality_metric_classes/presence_ratio.py
- spiketoolkit/validation/quality_metric_classes/quality_metric.py
- spiketoolkit/validation/quality_metric_classes/silhouette_score.py
- spiketoolkit/validation/quality_metric_classes/snr.py
- spiketoolkit/validation/quality_metric_classes/utils/validation_tools.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_list.py
- make `center` preprocessor more efficient
- use waveforms and amp params and **kwargs in postprocessing
- improved and completed curation and validaiton tests
- fix bug in get_unit_waveforms https://github.com/SpikeInterface/spiketoolkit/issues/314
- unify param dicts between postprocessing and validation modules
> Various updates

- spiketoolkit/postprocessing/postprocessing_tools.py
Change export_to_phy, removing raw file pathway in params.py.
There is no need and if file is moved raw data is not find anmymore.
> Update postprocessing_tools, export_to_phy

- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/quality_metric.py
> fixed unit ids bug

- spiketoolkit/validation/quality_metrics.py
> valid names given when metric name wrong

- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metrics.py
> sampling frequency fix

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
- for https://github.com/SpikeInterface/spikeextractors/pull/357
- and set `memmap` to True by default!
> Updates for spikextractors 

- spiketoolkit/postprocessing/postprocessing_tools.py
- `_compute_template_similarity` did nt consider the swap axis
- when `recompute_info` is True, also clear `pca_scores` features
- add warning message is recording is not filtered
@llobetv @Dradeliomecus you probably have a wrong similarity score in phy due to this! I suggest re-exporting to phy :)
> Fixes to compute similarity and recompute_info for phy

- spiketoolkit/validation/quality_metric_classes/isi_violation.py
min_isi default to 0.5 * 1 / fs
> min_isi new default

- spiketoolkit/postprocessing/__init__.py
- spiketoolkit/postprocessing/features.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/postprocessinglist.py
- spiketoolkit/tests/test_postprocessing.py
Hi! 
These are the TODO's I think:
-update docstring
-decide on loop structure (right now it loops over all units, computed features for all channels, then only saves the main features)
-polish output format (align with metrics)
-update kwargs
-make methods to compute single metrics
> (WIP) spikefeatures

- setup.py
- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/drift_metric.py
- spiketoolkit/validation/quality_metric_classes/firing_rate.py
- spiketoolkit/validation/quality_metric_classes/isi_violation.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/presence_ratio.py
- spiketoolkit/validation/quality_metric_classes/silhouette_score.py
Computation of metrics performed only on specified units. Identical values as doing all the units, but should be more efficient!
> subset of units improved to reduce computation

- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
Hi,
I implemented idx method for features in to_merge function,
Is the method I used is ok for you? 
Cheer,
Victor
> Update curationsortingextractor.py, merge_units

- spiketoolkit/postprocessing/postprocessing_tools.py
Sort spike indices before requesting snippets is slightly faster (esp. hdf5).
> small speed-up getting waveforms

- spiketoolkit/preprocessing/common_reference.py
Fixes this https://github.com/SpikeInterface/spiketutorials/issues/11
> CMR fix when channels are removed

- spiketoolkit/tests/test_curation_extractor.py
- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
- spiketoolkit/validation/quality_metric_classes/utils/thresholdcurator.py
Almost done. I wasn't sure how to integrate this with kwargs in the current dumping code. Any advice on this @alejoe91 ?
> curation dump WIP

- setup.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
https://github.com/SpikeInterface/spiketoolkit/issues/366
@llobetv  Can you test if this speeds up your processing? you can call export_t0_phy with the `n_jobs` argument (and that applies to waveforms and amplitudes).
> Added tests and parallel amplitude calculation

- spiketoolkit/postprocessing/postprocessing_tools.py
- if the recording is a `CacheRecordingExtractor` or a `BinDatRecordingExtractor`, avoid re-writing it to the phy folder (currently the path points to the file, but we could add an option to copy the file - faster than write_to_binary function)
- handle case when `waveforms` features are absent, `templates` are present, and no pc nor amplitudes are exported. In this case, bypass waveform extraction and just work on the templates. This case can happen if dumping to pkl excluding features, so the loaded object could have templates, but not waveforms
> Export to Phy: avoid copy binary and deal with missing info

- spiketoolkit/postprocessing/postprocessing_tools.py
- fixed `export_to_phy` when `copy_binary=False` and type is `BinDatRecordingExtractor`
> Fix export_to_phy copy_binary bug

- spiketoolkit/postprocessing/postprocessing_tools.py
Refractored and fixed some bugs in `get_unit_waveforms`
Might fix https://github.com/SpikeInterface/spiketoolkit/issues/405
> Fix get_unit_waveforms for all params

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/basepreprocessorrecording.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/clip.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/tests/test_preprocessing.py
The `BasePreprocessorRecordingExtractor` now takes care of:
- copying properties and epochs
- copying `is_filtered`
- implement `get_num_frames()`, `get_channel_ids()`, `get_sampling_frequency()`, `time_to_frame()`, and `frame_to_time()`
This removes a lot of duplicate code :)
> Implemented BasePreprocessorRecordingExtractor

- spiketoolkit/postprocessing/postprocessing_tools.py
This fixes a bug when waveforms are already computed on a subset of spikes and `recompute_info` is False. 
The export to phy did not raise errors, but reloading the phy sorted data fails. 
This patch checks, if available, that all waveforms have the same length as spike trains. If not, waveforms are recomputed (same as pc scores and amplitudes)
> Check waveforms shape in export to phy

- spiketoolkit/postprocessing/postprocessing_tools.py
Fixes https://github.com/SpikeInterface/spiketoolkit/issues/424
> Correct use unit_ids throughout postprocessing

- setup.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
Change related to https://github.com/SpikeInterface/spikemetrics/pull/25
> Add channel locations parameter to metric computing functions

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
> cast unit ids as list for pca_score

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
Fixes: https://github.com/SpikeInterface/spiketoolkit/issues/454
> Recompute amps if shapes do not match in export to phy

- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
CurationSortingExtractor now inherits tmp_folder from parent.
> CurationSortingExtractor inherits tmp_folder

- spiketoolkit/preprocessing/basepreprocessorrecording.py
- spiketoolkit/preprocessing/mask.py
- spiketoolkit/preprocessing/preprocessinglist.py
- spiketoolkit/tests/test_preprocessing.py
@lfrank does this look good? I removed the option to pass a None as a mask..
> Added mask preprocessor

- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/tests/test_preprocessing.py
Throws an error when `chunk_size` is `None` (not default)
> Add return_scaled to filter chunk

- spiketoolkit/utils.py
fix after discussion with @samuelgarcia  on the previous PR #470
> fix channel id to find the nearest channels

- spiketoolkit/preprocessing/common_reference.py
- add assert when the selecting annulus does not contain channels
- fix verbose option bug
> fix local CAR
