- spiketoolkit/comparison/sortingcomparison.py
Fix: spikes from sorting2 with multiple matches in sorting1 were not considered matches, this should be done as sorting1 is usually ground truth
Fix: the range tested was 2*delta_tp-1 frames long, changed now to the range -delta_tp//2 ... delta_tp//2
Improvement: deep-copy spike trains before counting, speed improvement when data is memmapped
Improvement: small change in matching method, slightly faster
> fixes in comparison function

- spiketoolkit/comparison/gathersortingcomparison.py
- spiketoolkit/comparison/sortingcomparison.py
This count how many units above threshold (95% by default) have been detected.
This is done on ['tp_rate', 'accuracy', 'sensitivity'].
Spikeforest have a similar metric but not implemented in spiketoolkit.
It is important to have it.
> Add new performence table : count nb_units above threshold

- spiketoolkit/comparison/comparisontools.py
- spiketoolkit/comparison/multisortingcomparison.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/sorters/kilosort/kilosort.py
- spiketoolkit/sorters/kilosort2/kilosort2.py
- updated export to phy function with improved pca extraction and group settings (working with latest `gloo` phy branch)
-  fixed channel mismatch in get_unit_max_channel
- for kilosort and kilosort2: if location is not given, linear location is assumed
- in multisorting comparison: `compare_spiketrains` checks that spikes have not be labeled as TP before
> fixes to posptocessing, kilosort, and multicomp

- .travis.yml
- spiketoolkit/__init__.py
- spiketoolkit/sorters/mountainsort4/mountainsort4.py
I have released tridesclous to 1.1.0.
So I force travis.
We should also do the same for HS2 and mountainsort.
> Force tridesclous=1.1.0

- spiketoolkit/comparison/multisortingcomparison.py
When looking for the maximum edge (agreement) between units, the order should be of the original graph needs to be kept, otherwise the edges might not be found in the original graph
> MultiSortingComparison bug fix

- .travis.yml
- spiketoolkit/sorters/tridesclous/tridesclous.py
I am working on parameters for tridesclous sorter.
DO NOT MERGE NOW because this is depend on tridesclous==1.2.0 that will be release this week.
The main change is parameters name to make less ambiguous units (second vs sample vs ms).
After this could it be possible to make a release of spiketoolkit soon, so I could be able to propagate changes in spikeforest wrapper.
> Tridesclous

- spiketoolkit/sorters/klusta/config_default.prm
- spiketoolkit/sorters/klusta/klusta.py
In actual implementation a binary file for klusta MUST be ".dat" now it is can be any extention (.raw, .bin)
> Change logic to avoid to force .dat for binary

- spiketoolkit/comparison/groundtruthcomparison.py
- spiketoolkit/comparison/tests/test_groundtruthcomparison.py
I have just discover a string bug in get_redundant_units
The logic was totally false.
Sorry this is my fault.
This should be fixed now.
We will need to release again before the meeting for this.
@alejoe91 
@colehurwitz
> Strong bug in get_redundant_units

- spiketoolkit/sorters/spyking_circus/config_default.params
- spiketoolkit/sorters/spyking_circus/spyking_circus.py
I copied the changes submitted to SpikeForest, in order for the two repos to be in sync. Note that current version of SC is now 0.8.0, available with pip/conda/docker. These changes are not meant to turn the code into a pure automatic software. They are just slightly decreasing the number of clusters, and further investigation should be performed to turn it into a pure automatic workflow.
> Same changes as in SpikeForest

- .travis.yml
- spiketoolkit/sorters/herdingspikes/herdingspikes.py
Now performs scaling and bandpass by default as this is required in almost all cases. This can be turned off for Biocam data for a slight speed increase.
> New default parameters for next release

- spiketoolkit/comparison/groundtruthcomparison.py
@alejoe91 @colehurwitz @mhhennig @magland 
This change the behavior of counting in the ground truth context.
It was discussed in Edimburgh.
Before the counting was done on **_unit_map12** (aka hugarian assignement) now it is done on the **_best_match_units_12** (the best match).
It could change a bit the metrics. 
Are we all agree on that ?
Tell me.
> Use best match instaed of hugarian match for couting in GT context.

- spiketoolkit/preprocessing/common_reference.py
@alejoe91  I didn't change the functionality, but I thought it would be better if reference channels was always a list rather than an integer or a list (better to have one type). If the list is length 1, I just store it as an integer so your old code is compatible. This will also help with future static type checking.
> Changed common reference to accept only list for reference channels

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/postprocessinglist.py
- implemented `get_unit_amplitudes` in postprocessing_tools
@colehurwitz to get kilosort2-like amplitudes you can use the `method=relative` arg. In that case, amplitudes are returned as ratio with respect to the template median (more robust).
> Added get_unit_amplitudes

- spiketoolkit/validation/metric_calculator.py
This code still breaks when `unit_ids` is supplied. The trouble is that the metric_data is computed for all units in an extractor, regardless of `unit_ids`.
> Exclude units without spikes from all calculations (still a bug here)

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/whiten.py
- spiketoolkit/tests/test_preprocessing.py
- moved out the butter filter creation in the init
- cache option now filters all the data and dumps it into a bin recording
Should fix:
https://github.com/SpikeInterface/spiketoolkit/issues/249  https://github.com/SpikeInterface/spiketoolkit/issues/248
I tested the performance on 120s 16 channels:
**Default filter**
```
rec_f = st.preprocessing.bandpass_filter(rec)
t_start = time.time()
rec_f.get_traces()
print(time.time() - t_start)
2.017151117324829 s
t_start = time.time()
wf1 = st.postprocessing.get_unit_waveforms(rec_f, sort)
print(time.time() - t_start)
2.023608446121216 s
```
**Cache** - the filtering is performed at initialization and dumped to file (a bit slower)
```
t_start = time.time()
rec_c = st.preprocessing.bandpass_filter(rec, cache=True)
print(time.time() - t_start) …
```
> Improved filtering

- spiketoolkit/curation/curationsortingextractor.py
- spiketoolkit/curation/threshold_firing_rate.py
- spiketoolkit/curation/threshold_isi_violations.py
- spiketoolkit/curation/threshold_num_spikes.py
- spiketoolkit/curation/threshold_presence_ratio.py
- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/curation/thresholdcurator.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/__init__.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_tools.py
This allows to run metrics with a few number of spikes
- postprocessing tools can return indexes of spikes used to compute waveforms, amplitudes, and pc scores
- the indexes are used to extract two extra set otf spike_clusters and spike_times: spike_times_pca, spike_times_amps
- metrics using amplitudes or pca use this subsets of spike times (to get epochs idxs) and spike clusters and pass them to spikemetrics functions
> Fix metrics when max_num_spikes and pca is less than inf

- spiketoolkit/curation/threshold_snr.py
- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
Added optional bandpass filter the quality metrics:
Added filter arguments to `__init__`
Added filter arguments to `set_recording`
Added filter arguments to `compute_amplitudes`
Added filter arguments to `compute_pca_scores`
Added filter arguments to `compute_all_quality_metric_data`
The actual filter is performed in the `set_recording` function if `apply_filter` is `True` (this is `True` by default).
I propagated the changes to all functional call (ugh) and to the SNR curator.
> added optional bandpass filter for metrics

- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/filterrecording.py
This ensures that ref_channels is always a list when calling `get_traces`. It fixes https://github.com/SpikeInterface/spiketoolkit/issues/265
> Fix common reference when ref_channels is int

- spiketoolkit/curation/threshold_num_spikes.py
- spiketoolkit/tests/test_curation.py
I can't remove the sampling frequency requirement from the metric_calculator... but I can at least remove it from the curation tool. Tricky. Ideally, sampling_frequency should never be needed when computing num spikes.
> removed sampling frequency from curation num spikes

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_postprocessing.py
Using the `max_channels` arg (default=1) the user can return a least of the channels with largest amplitudes for each unit.
Should help for this: https://github.com/SpikeInterface/spikewidgets/issues/46
> get_unit_max_channels can return more than one channel

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/validation/metric_calculator.py
- spiketoolkit/validation/quality_metrics.py
We had the feature of returning a single list (instead of a list of list) when the number of units was 1. I removed this since it causes issues for downstream functions. Had to adjust a bunch of code to make it work.
@alejoe91 can you check elsewhere to see if this may cause problems? No problems in spiketoolkit I think, but not sure about widgets.
> removed returning single list when unit ids is 1

- spiketoolkit/preprocessing/common_reference.py
this fixes a bug when running a pipeline with a filter and a common reference processing that re-references groups by single channels
> Fix bug in single reference by groups

- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/tests/test_preprocessing.py
- when channel ids is given, rereferencing is done using correct channels before returning a subset of the channels https://github.com/SpikeInterface/spiketoolkit/issues/293
- added `dtype` option https://github.com/SpikeInterface/spiketoolkit/issues/295
> Fixes to common reference

- spiketoolkit/postprocessing/postprocessing_tools.py
Lowered the default params in postprocessing to be consistent with metric calculation. Also, since infinite waveforms are too memory intensive, lowering the default is important.
> lowered default params

- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/clip.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/preprocessinglist.py
- spiketoolkit/preprocessing/transform.py
- spiketoolkit/preprocessing/transform_traces.py
- spiketoolkit/tests/test_preprocessing.py
- For standardization, `transform_traces` and `clip_traces` are renamed `transform` and `clip`.
- Added a preprocessor to `center` the recordings by removing the mean channel-wise
- the filters fail if the dtype is `uint`. Added a check that transforms the data to `int` in that case by removing the appropriate offset
> Some fixes and refractor

- spiketoolkit/curation/__init__.py
- spiketoolkit/curation/threshold_metrics.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/parameter_dictionaries.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_list.py
Instead of passing several parameters for the `validation` and `curation` functions, now one can use `**kwargs`. To get a list of available `**kwargs`, we can refer to the docstrings or use the function `st.validation.get_kwargs_params()` or `st.curation.get_kwargs_params()`
> Simplify validation and curation argument passing using kwargs

- spiketoolkit/postprocessing/postprocessing_tools.py
Hi :)
If compute_pc_features was False templates_ind.py was wrong. 
Because it used pc_feature_ind to be calculated and that the new method for calculate template ind without pca_ind was wrong (work with template without all channels). 
So I use channel_list return when waveform are exctracted that appear to be the same as pc_feature_ind. 
I don't remove the old method l 1462 but maybe we can?
> fix export_to_phy template_ind

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/postprocessinglist.py
- spiketoolkit/sortingcomponents/detection.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_sortingcomponents.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- added `compute_channel_spiking_activity` in `postprocessing`
- waveforms and pca_scores save the channels on which they are computed as a property
- fixed a bug in compute_num_spikes
- fixed bug in computing max channels for waveforms/templates
> Compute channel activity

- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/resample.py
the `get_dtype` in the base recording extractor attempts to extract one frame with get traces. This fails with some filters. Better to store the dtype and cast the returned traces
> Override `get_dtype` in FilterRecordingExtractor and ResampleRecordingExtractor

- .travis.yml
- setup.py
- spiketoolkit/curation/threshold_metrics.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/quality_metric_classes/amplitude_cutoff.py
- spiketoolkit/validation/quality_metric_classes/d_prime.py
- spiketoolkit/validation/quality_metric_classes/drift_metric.py
- spiketoolkit/validation/quality_metric_classes/firing_rate.py
- spiketoolkit/validation/quality_metric_classes/isi_violation.py
- spiketoolkit/validation/quality_metric_classes/isolation_distance.py
- spiketoolkit/validation/quality_metric_classes/l_ratio.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
- spiketoolkit/validation/quality_metric_classes/nearest_neighbor.py
- spiketoolkit/validation/quality_metric_classes/num_spikes.py
- spiketoolkit/validation/quality_metric_classes/parameter_dictionaries.py
- spiketoolkit/validation/quality_metric_classes/presence_ratio.py
- spiketoolkit/validation/quality_metric_classes/quality_metric.py
- spiketoolkit/validation/quality_metric_classes/silhouette_score.py
- spiketoolkit/validation/quality_metric_classes/snr.py
- spiketoolkit/validation/quality_metric_classes/utils/thresholdcurator.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_list.py
WIP on removing epochs from quality metrics --> replacing them with manual subsorting and subrecording extractors.
@alejoe91 I ran into a little issue with the `waveforms_idxs`  spike feature... for some reason it is stored as a list instead of a numpy array so when you call get_epoch on a sorting extractor with this feature, it will throw an error. I can't find where this feature is set. Could you point me to the relevant code?
> Removing epochs from quality metrics [WIP]

- setup.py
@colehurwitz remember to merge to master before merging a PR
`spikefeatures` was removed in the setup.py
https://github.com/SpikeInterface/spiketoolkit/blob/7a16b0e4e5b3d67dde66b9ef43ad94312091c2f1/setup.py#L26
> Re-add spikefeatures in setup.py

- spiketoolkit/tests/test_curation_extractor.py
- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
#355 
Split and merge in the `CurationSortingExtractor` now return the new unit_ids as requested.
> return unit ids curation sorting extractor

- spiketoolkit/validation/quality_metric_classes/metric_data.py
The use of `set` and `intersection` was scrampling the order of the unit ids, causing indexing error: https://github.com/SpikeInterface/spiketoolkit/issues/378
> Fix unit ids ordering in quality metrics

- spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py
Currently get_sample_frequency() returns the sample frequency from parent, although the class has the ability to set a new sample frequency. This was reconciled by:
Modifying **curationsortingextractor.py** :
removing get sampling rate method (let it inherit it's parent method automatically)
initializing sampling rate in constructor: `self._sampling_frequency = parent_sorting.get_sampling_frequency()`
This addresses issue #393 and this PR was requested by @alejoe91
> Fixed get_sample_frequency

- spiketoolkit/postprocessing/postprocessing_tools.py
Fixes the wrong file name in `get_unit_amplitudes()`
> Fix amplitudes file names

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/clip.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/rectify.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/remove_bad_channels.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform.py
Fixes #406 by correctly copying over epoch information after preprocessing.
> fix disappearing epochs in preprocessors

- spiketoolkit/postprocessing/__init__.py
- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/sortingcomponents/detection.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_sortingcomponents.py
- Add function to compute center of mass (COM) based on units' amplitudes `compute_unit_centers_of mass`
- Refractor of `compute_channel_spiking_activity`: instead of setting the `activity` property, it now sets both the `spike_rate` and `spike_amplitude` properties (required a modification of the `st.sortingcomponents.detect_spikes` function). In addition, a chunking mechanism for computing channel activity and detecting spikes is implemented, making parallel processing more efficient.
- Add tests for: `compute_unit_pca_scores`, `compute_channel_spiking_activity`, and `compute_unit_coms`
**NOTE**: this PR will break the spikewidgets `plot_activity_map`. With the next spiketoolkit and spikewidgets release we'll need to use `spiketoolkit>=0.7.2` as requirement
> Compute COM and refractor spiking activity

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/sortingcomponents/detection.py
- spiketoolkit/tests/test_postprocessing.py
- Use broadcasting to perform channel-wise detection
- Remove `simple` method in `compute_channel_spiking_activity` as the detection method is more accurate and computationally as efficient
> Improved spike detecion

- spiketoolkit/curation/__init__.py
- spiketoolkit/curation/threshold_metrics.py
- spiketoolkit/tests/test_curation.py
- spiketoolkit/tests/test_validation.py
- spiketoolkit/validation/quality_metric_classes/noise_overlap.py
- spiketoolkit/validation/quality_metrics.py
- spiketoolkit/validation/validation_list.py
Implements noise overlap metric from the [Mountainsort paper](http://dx.doi.org/10.1016/j.neuron.2017.08.030). The implementation is based on ml_ms4alg: https://github.com/magland/ml_ms4alg/blob/master/ml_ms4alg/compute_noise_overlap.py
@magland @lfrank 
@colehurwitz I didn't implement it in spikemetrics because it needs the recordings to get random snippets. Is it possible to do so in spikemetrics as well?
> Noise overlap metric

- spiketoolkit/validation/quality_metric_classes/noise_overlap.py
Pull request related to this issue: https://github.com/SpikeInterface/spiketoolkit/issues/425#issue-761961334
> Limit num_knn to total possible neighbors when computing noise overlap metric

- spiketoolkit/validation/quality_metric_classes/snr.py
In case traces are filtered but with an offset, the mad computation is biased. This PR removes the mean of the traces before computing mad
> Fix MAD computation by removing mean

- spiketoolkit/preprocessing/remove_artifacts.py
Make a copy of memmapped traces in memory to be able to access it for editing when the traces are requested using the get_traces() method
Fixes issue #448 - ValueError: assignment destination is read-only
> RemoveArtifacts: Copy traces to fix write access

- spiketoolkit/postprocessing/postprocessing_tools.py
Added the option to set filter_flag to False to not display the warning on using export_to_phy using a non-filtered recording.
> Added filter_flag to export_to_phy

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/highpass_filter.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/preprocessinglist.py
- spiketoolkit/tests/test_postprocessing.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
Runs fast as simple Butterworth order 1 filter, use it to remove slow, LFP-like fluctutations (also has fft version). Faster than the bandpass. Note that generally the fft based method seems slower (it's default in the bandpass).
> Simple fast high pass filter

- setup.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/tests/test_preprocessing.py
Add 'mode' input argument to remove_artifacts(). Default is 'zeros' (old behaviour). If 'linear', implements linear interpolation between pre and post artifact points. If 'cubic' - implements cubit spline interpolation.
Additional input 'fit_sample_spacing' determines how far apart sample points are taken for creating the spline fit that is used to fill in the gap (default is 1 ms). Shorter sample intervals lead to better continuation locally, but may lead to steeper fit slopes with more high frequency content.
Related to issue #451
> Add artifact removal modes (linear & cubic interpolation)

- spiketoolkit/postprocessing/postprocessing_tools.py
- spiketoolkit/postprocessing/utils.py
- spiketoolkit/validation/quality_metric_classes/metric_data.py
Added the ability to specify a maximum number of spikes per unit to fit the pca while exporting to phy.
I set the default number of spikes to 5,000, but you can change it to whatever you want.
I checked using my dataset, and it works!
The PCA looks pretty much the same as the one when I fit on all the waveforms.
> Added max_spikes_for_pca_fit argument

- spiketoolkit/preprocessing/bandpass_filter.py
- spiketoolkit/preprocessing/basepreprocessorrecording.py
- spiketoolkit/preprocessing/blank_saturation.py
- spiketoolkit/preprocessing/center.py
- spiketoolkit/preprocessing/clip.py
- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/preprocessing/filterrecording.py
- spiketoolkit/preprocessing/highpass_filter.py
- spiketoolkit/preprocessing/mask.py
- spiketoolkit/preprocessing/normalize_by_quantile.py
- spiketoolkit/preprocessing/notch_filter.py
- spiketoolkit/preprocessing/remove_artifacts.py
- spiketoolkit/preprocessing/resample.py
- spiketoolkit/preprocessing/transform.py
- spiketoolkit/preprocessing/whiten.py
- Some preprocessors compute parameters in the init (e.g. center, transform, etc.). These will not support `return_scaled=False`
- Propagated `return_scaled` to filter functions
> Fix return scaled 

- spiketoolkit/sortingcomponents/detection.py
- spiketoolkit/tests/test_sortingcomponents.py
The tests were not running properly because `chunk_mb` was too large. The spikes detected in each chunk must be shifted by `chunk['istart']`
> Fix detectionfor multiple chunk and improve tests

- spiketoolkit/preprocessing/common_reference.py
- spiketoolkit/tests/test_preprocessing.py
- spiketoolkit/utils.py
Remarks : 
- I did not implemented a group option as you (@alejoe91) said in the issue it should be something apply on all channels. Seems weird however - should I add one ? 
- I am still unsure that it is logical to have the local_radius option in common_reference as it is an option only for the local filtering. 
close   #390 
Description of the test case added : 
Also, a little refactoring/clean-up of this code would be nice. I can do it in other PR if you want. 
For example, I would put this code in an external private method instead of being repeat  3 times. (Tell me if I am overstepping here :) )
```
for g in self._groups:
new_chans = []
for chan in g:
if chan in self._recording.get_channel_ids():
new_chans.append(chan)
new_groups.append(new_chans)
```
Also, I am not an expert of …
> Issue 390 local car implementation

- spiketoolkit/preprocessing/common_reference.py
This fixes a bug occurring when multiple reference groups are used, but `get_traces` is called on a subset of channels that are only in a sub group
> Fix CMR when using groups and subselection of channels

- spiketoolkit/postprocessing/postprocessing_tools.py
Fixes a bug in assigning the right spike rates and amplitudes in `postprocessing.compute_channel_spiking_activity` when some channels have 0 spikes detected
> Fix channel idxs in spike detection

- spiketoolkit/postprocessing/postprocessing_tools.py
This PR is fixing this issue: https://github.com/SpikeInterface/spikeinterface/issues/191#issuecomment-879023849
The get_unit_amplitudes function was missing some optional params. This is a problem when non-default values are used, because the waveforms are extracted using the optional values and get_unit_amplitudes is slicing an array based on the default values.
> Add missing parameters to get_unit_amplitudes
